---
- name: Install base packages
  ansible.builtin.apt:
    name:
      - vim
      - htop
      - curl
      - wget
      - git
      - net-tools
      - dnsutils
      - jq
      - tree
      - unzip
      - tmux
      - ncdu
      - rsync
      - logrotate
      - cron
      - bash-completion
      - software-properties-common
      - apt-transport-https
      - gnupg
      - lsb-release
      - ca-certificates
    state: present
